Feilh친ndtering (Heidi)
==============

**游눠 L칝ringsm친l:** _I dette avsnittet l칝rer du hvordan du kan h친ndtere feil som oppst친r i programmet og dermed unng친 at programmet kr칝sjer._

I program kan det ganske lett oppst친 feilsituasjoner som gj칮r at programmet kr칝sjer og avslutter, dette kalles unntak, eller `exception` p친 engelsk. Kanskje har du alt opplevd det selv i dette kurset. 

Noen ganger kan det v칝re riktig at programmet avslutter seg selv, mens andre ganger vil vi redde inn situasjonen slik at programmet kan forsette selv om det skjedde noe feil eller uventet. En forutsetning for at vi skal kunne klare 친 redde inn feil n친r de oppst친r er at vi vet hva programmet b칮r gj칮re istedet for det det fors칮kte 친 gj칮re.

La oss starte med et lite program som tar inn to tall, `a` og `b`, som input fra brukeren, og printer ut resultatet av `a/b`.

kopier f칮lgende program i en `.py`-fil, og kj칮r programmet. 

```python
while True: 
    a = float(input("Tall a: "))
    b = float(input("Tall b: "))
    resultat = a/b
    print(f"a/b er {resultat}")

```

Dette er visst en evig dele-maskin. Test ut programmet med ulike input. Hva skjer om du skriver inn bokstaver eller om du setter b til 친 v칝re tallet 0?

Forh친pentligvis fikk du programmet til 친 avslutte uventet fordi det oppsto et unntak. Kanskje ble det skrevet ut noe tekst i terminalen ala dette?

```
ZeroDivisionError: float division by zero
```

```
ValueError: could not convert string to float: 'hallo'
```


 I stedet for at programmet br친tt avslutter kan vi h친ndtere feilene og g친 videre. Det fins en egen type konstruksjon for dette, der n칮kkelordene `try` og `except` brukes. Den vanligste og mest grunnleggende bruksm친ten er som f칮lgende:
```python
try:
    # her er koden det kan skje unntak i
except Exception:
    # her kan vi gi beskjed til brukeren om unntaket og eventuelt gj칮re det som trengs for at programmet kan fortsette
```

La oss starte med det enkleste vi kan gj칮re for redde programmet v친rt fra 친 kr칝sje. Da setter vi all kode som kan kr칝sje inni en `try`-blokk, og skrive ut en feilmelding til brukeren i `except`-blokka: 

```python
while True: 
    try:
        a = float(input("Tall a: "))
        b = float(input("Tall b: "))
        resultat = a/b
        print(f"a/b er {resultat}")
    except Exception:
        print("Det skjedde noe feil, pr칮v igjen!")
```

Test ut denne endringen i programmet. Hva skjer n친 om man deler p친 0 eller skriver inn noe som ikke er tall?

Hva som er riktig 친 gj칮re n친r det oppst친r unntak vil avhenge av hva programmet gj칮r og hva slags type feil det Program som interagerer med brukere b칮r pr칮ve 친 gi brukere hjelpsom informasjon om hva som har skjedd og mulighet for 친 fortsette programmet. Programmet v친rt kr칝sjer ikke lenger, men vi kan gj칮re mer for 친 hjelpe brukeren med 친 forst친 hva som er feil. I blokka `except Exception` fanges n친 alle slags typer unntak, og vi kan fortelle brukeren noe mer om akkurat hva som gikk galt. 



- Hva gj칮r vi hvis det ikke finnes en fil?
    - Hva kan g친 feil: fila finnes ikke, feil filnavn, feil tillatelser, et annet program holder i filh친ndtaket.
- Unntak (exceptions), try/except/finally, raise.
- Situasjoner hvor man returnerer to verdier, men 칠n av indikerer en feil.
    - _Kun hvis det er plass til dette_
- Skrive ut med print(file=sys.stderr)

_Tips. `with` som vi akkurat har l칝rt om, er egentlig bare en snedig variant av try/except/finally._
